# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  schemas:
    ProductParam:
      type: object
      properties:
        name:
          $ref: '#/components/models/Product/name'
        title:
          $ref: '#/components/models/Product/title'
        description:
          $ref: '#/components/models/Product/description'
        price:
          $ref: '#/components/models/Product/price'
    Product:
      allOf:
      - $ref: '#/components/schemas/ProductParam'
      - type: object
        properties:
          _id:
            $ref: '#/components/models/Product/_id'
          discountPercentage:
            $ref: '#/components/models/Product/discountPercentage'
          published:
            $ref: '#/components/models/Product/published'
          adminAccountId:
            $ref: '#/components/models/Product/adminAccountId'
          purchaseCount:
            $ref: '#/components/models/Product/purchaseCount'
          createdAt:
            $ref: '#/components/schemas/FieldCreatedAt'
          updatedAt:
            $ref: '#/components/schemas/FieldUpdatedAt'
  