# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responseBody:
    ProductBanner:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductBanner'